dist: trusty
sudo: required

language: node_js
node_js:
  - 10

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - libegl1-mesa-dev
      - libgles2-mesa-dev

before_install:
  - |
    if [ ! -d "$HOME/SDL2-2.0.8" ]; then
      travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.8.tar.gz | tar xz --directory "$HOME"
      cd "$HOME/SDL2-2.0.8"
      ./configure
      make
    fi
    cd "$HOME/SDL2-2.0.8"
    sudo make install
    if [ ! -d "$HOME/SDL2_mixer-2.0.4" ]; then
      travis_retry curl -L https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4.tar.gz | tar xz --directory "$HOME"
      cd "$HOME/SDL2_mixer-2.0.4"
      ./configure --disable-sdltest --with-sdl-prefix=/usr/local
      make
    fi
    cd "$HOME/SDL2_mixer-2.0.4"
    sudo make install
    cd $TRAVIS_BUILD_DIR
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++

install:
  - export npm_config_sdl_include_path=/usr/local/include/SDL2
  - export npm_config_sdl_library_path=/usr/local/lib
  - export npm_config_with_sdl_mixer=true
  - npm install

script:
  - export LD_LIBRARY_PATH=/usr/local/lib
  - npm test

cache:
  directories:
    - $HOME/SDL2-2.0.8
    - $HOME/SDL2_mixer-2.0.4
