dist: trusty
sudo: required

language: node_js
node_js:
  - 10

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - libegl1-mesa-dev
      - libgles2-mesa-dev

before_install:
  - |
    travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.8.tar.gz | tar xz
    cd SDL2-2.0.8
    ./configure
    make
    sudo make install
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++

install:
  - export npm_config_sdl_include_path=/usr/include/SDL2
  - export npm_config_sdl_library_path=/usr/lib/x86_64-linux-gnu
  - npm install

script:
  - npm test
